# Copyright 2019 Google Inc.
# Copyright 2019 Alan Pearce
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

alias k='kubectl'
alias ka='kubectl apply --recursive -f'
alias kex='kubectl exec -i -t'
alias klo='kubectl logs -f'
alias kp='kubectl proxy'
alias kg='kubectl get'
alias kt='kubectl top'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias kgpo='kubectl get pods'
alias ktpo='kubectl top pods'
alias kdpo='kubectl describe pods'
alias krmpo='kubectl delete pods'
alias kgdep='kubectl get deployment'
alias kddep='kubectl describe deployment'
alias krmdep='kubectl delete deployment'
alias kgsvc='kubectl get service'
alias kdsvc='kubectl describe service'
alias krmsvc='kubectl delete service'
alias kging='kubectl get ingress'
alias kding='kubectl describe ingress'
alias krming='kubectl delete ingress'
alias kgcm='kubectl get configmap'
alias kdcm='kubectl describe configmap'
alias krmcm='kubectl delete configmap'
alias kgsec='kubectl get secret'
alias kdsec='kubectl describe secret'
alias krmsec='kubectl delete secret'
alias kgjo='kubectl get jobs'
alias kdjo='kubectl describe jobs'
alias krmjo='kubectl delete jobs'
alias kgcjo='kubectl get cronjobs'
alias kdcjo='kubectl describe cronjobs'
alias krmcjo='kubectl delete cronjobs'
alias kgno='kubectl get nodes'
alias ktno='kubectl top nodes'
alias kdno='kubectl describe nodes'
alias kgns='kubectl get namespaces'
alias kdns='kubectl describe namespaces'
alias krmns='kubectl delete namespaces'
alias kgpv='kubectl get persistentvolume'
alias kdpv='kubectl describe persistentvolume'
alias krmpv='kubectl delete persistentvolume'
alias kgpvc='kubectl get persistentvolumeclaim'
alias kdpvc='kubectl describe persistentvolumeclaim'
alias krmpvc='kubectl delete persistentvolumeclaim'
alias kgss='kubectl get statefulset'
alias kdss='kubectl describe statefulset'
alias krmss='kubectl delete statefulset'
alias kgoyaml='kubectl get -o=yaml'
alias kgpooyaml='kubectl get pods -o=yaml'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias kgjooyaml='kubectl get jobs -o=yaml'
alias kgcjooyaml='kubectl get cronjobs -o=yaml'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgpvoyaml='kubectl get persistentvolume -o=yaml'
alias kgpvcoyaml='kubectl get persistentvolumeclaim -o=yaml'
alias kgssoyaml='kubectl get statefulset -o=yaml'
alias kgowide='kubectl get -o=wide'
alias kgpoowide='kubectl get pods -o=wide'
alias kgdepowide='kubectl get deployment -o=wide'
alias kgsvcowide='kubectl get service -o=wide'
alias kgingowide='kubectl get ingress -o=wide'
alias kgcmowide='kubectl get configmap -o=wide'
alias kgsecowide='kubectl get secret -o=wide'
alias kgjoowide='kubectl get jobs -o=wide'
alias kgcjoowide='kubectl get cronjobs -o=wide'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgpvowide='kubectl get persistentvolume -o=wide'
alias kgpvcowide='kubectl get persistentvolumeclaim -o=wide'
alias kgssowide='kubectl get statefulset -o=wide'
alias kgojson='kubectl get -o=json'
alias kgpoojson='kubectl get pods -o=json'
alias kgdepojson='kubectl get deployment -o=json'
alias kgsvcojson='kubectl get service -o=json'
alias kgingojson='kubectl get ingress -o=json'
alias kgcmojson='kubectl get configmap -o=json'
alias kgsecojson='kubectl get secret -o=json'
alias kgjoojson='kubectl get jobs -o=json'
alias kgcjoojson='kubectl get cronjobs -o=json'
alias kgnoojson='kubectl get nodes -o=json'
alias kgnsojson='kubectl get namespaces -o=json'
alias kgpvojson='kubectl get persistentvolume -o=json'
alias kgpvcojson='kubectl get persistentvolumeclaim -o=json'
alias kgssojson='kubectl get statefulset -o=json'
alias kgoname='kubectl get -o=name'
alias kgpooname='kubectl get pods -o=name'
alias kgdeponame='kubectl get deployment -o=name'
alias kgsvconame='kubectl get service -o=name'
alias kgingoname='kubectl get ingress -o=name'
alias kgcmoname='kubectl get configmap -o=name'
alias kgseconame='kubectl get secret -o=name'
alias kgjooname='kubectl get jobs -o=name'
alias kgcjooname='kubectl get cronjobs -o=name'
alias kgnooname='kubectl get nodes -o=name'
alias kgnsoname='kubectl get namespaces -o=name'
alias kgpvoname='kubectl get persistentvolume -o=name'
alias kgpvconame='kubectl get persistentvolumeclaim -o=name'
alias kgssoname='kubectl get statefulset -o=name'
alias kgall='kubectl get --all-namespaces'
alias kdall='kubectl describe --all-namespaces'
alias kgpoall='kubectl get pods --all-namespaces'
alias kdpoall='kubectl describe pods --all-namespaces'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kgsvcall='kubectl get service --all-namespaces'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kgingall='kubectl get ingress --all-namespaces'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kgjoall='kubectl get jobs --all-namespaces'
alias kdjoall='kubectl describe jobs --all-namespaces'
alias kgcjoall='kubectl get cronjobs --all-namespaces'
alias kdcjoall='kubectl describe cronjobs --all-namespaces'
alias kgnsall='kubectl get namespaces --all-namespaces'
alias kdnsall='kubectl describe namespaces --all-namespaces'
alias kgpvall='kubectl get persistentvolume --all-namespaces'
alias kdpvall='kubectl describe persistentvolume --all-namespaces'
alias kgpvcall='kubectl get persistentvolumeclaim --all-namespaces'
alias kdpvcall='kubectl describe persistentvolumeclaim --all-namespaces'
alias kgssall='kubectl get statefulset --all-namespaces'
alias kdssall='kubectl describe statefulset --all-namespaces'
alias kgsl='kubectl get --show-labels'
alias kgposl='kubectl get pods --show-labels'
alias kgdepsl='kubectl get deployment --show-labels'
alias krmall='kubectl delete --all'
alias krmpoall='kubectl delete pods --all'
alias krmdepall='kubectl delete deployment --all'
alias krmsvcall='kubectl delete service --all'
alias krmingall='kubectl delete ingress --all'
alias krmcmall='kubectl delete configmap --all'
alias krmsecall='kubectl delete secret --all'
alias krmjoall='kubectl delete jobs --all'
alias krmcjoall='kubectl delete cronjobs --all'
alias krmnsall='kubectl delete namespaces --all'
alias krmpvall='kubectl delete persistentvolume --all'
alias krmpvcall='kubectl delete persistentvolumeclaim --all'
alias krmssall='kubectl delete statefulset --all'
alias kgw='kubectl get --watch'
alias kgpow='kubectl get pods --watch'
alias kgdepw='kubectl get deployment --watch'
alias kgsvcw='kubectl get service --watch'
alias kgingw='kubectl get ingress --watch'
alias kgcmw='kubectl get configmap --watch'
alias kgsecw='kubectl get secret --watch'
alias kgjow='kubectl get jobs --watch'
alias kgcjow='kubectl get cronjobs --watch'
alias kgnow='kubectl get nodes --watch'
alias kgnsw='kubectl get namespaces --watch'
alias kgpvw='kubectl get persistentvolume --watch'
alias kgpvcw='kubectl get persistentvolumeclaim --watch'
alias kgssw='kubectl get statefulset --watch'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgjooyamlall='kubectl get jobs -o=yaml --all-namespaces'
alias kgcjooyamlall='kubectl get cronjobs -o=yaml --all-namespaces'
alias kgnsoyamlall='kubectl get namespaces -o=yaml --all-namespaces'
alias kgpvoyamlall='kubectl get persistentvolume -o=yaml --all-namespaces'
alias kgpvcoyamlall='kubectl get persistentvolumeclaim -o=yaml --all-namespaces'
alias kgssoyamlall='kubectl get statefulset -o=yaml --all-namespaces'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgjoalloyaml='kubectl get jobs --all-namespaces -o=yaml'
alias kgcjoalloyaml='kubectl get cronjobs --all-namespaces -o=yaml'
alias kgnsalloyaml='kubectl get namespaces --all-namespaces -o=yaml'
alias kgpvalloyaml='kubectl get persistentvolume --all-namespaces -o=yaml'
alias kgpvcalloyaml='kubectl get persistentvolumeclaim --all-namespaces -o=yaml'
alias kgssalloyaml='kubectl get statefulset --all-namespaces -o=yaml'
alias kgwoyaml='kubectl get --watch -o=yaml'
alias kgpowoyaml='kubectl get pods --watch -o=yaml'
alias kgdepwoyaml='kubectl get deployment --watch -o=yaml'
alias kgsvcwoyaml='kubectl get service --watch -o=yaml'
alias kgingwoyaml='kubectl get ingress --watch -o=yaml'
alias kgcmwoyaml='kubectl get configmap --watch -o=yaml'
alias kgsecwoyaml='kubectl get secret --watch -o=yaml'
alias kgjowoyaml='kubectl get jobs --watch -o=yaml'
alias kgcjowoyaml='kubectl get cronjobs --watch -o=yaml'
alias kgnowoyaml='kubectl get nodes --watch -o=yaml'
alias kgnswoyaml='kubectl get namespaces --watch -o=yaml'
alias kgpvwoyaml='kubectl get persistentvolume --watch -o=yaml'
alias kgpvcwoyaml='kubectl get persistentvolumeclaim --watch -o=yaml'
alias kgsswoyaml='kubectl get statefulset --watch -o=yaml'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgjoowideall='kubectl get jobs -o=wide --all-namespaces'
alias kgcjoowideall='kubectl get cronjobs -o=wide --all-namespaces'
alias kgnsowideall='kubectl get namespaces -o=wide --all-namespaces'
alias kgpvowideall='kubectl get persistentvolume -o=wide --all-namespaces'
alias kgpvcowideall='kubectl get persistentvolumeclaim -o=wide --all-namespaces'
alias kgssowideall='kubectl get statefulset -o=wide --all-namespaces'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgjoallowide='kubectl get jobs --all-namespaces -o=wide'
alias kgcjoallowide='kubectl get cronjobs --all-namespaces -o=wide'
alias kgnsallowide='kubectl get namespaces --all-namespaces -o=wide'
alias kgpvallowide='kubectl get persistentvolume --all-namespaces -o=wide'
alias kgpvcallowide='kubectl get persistentvolumeclaim --all-namespaces -o=wide'
alias kgssallowide='kubectl get statefulset --all-namespaces -o=wide'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias kgslowide='kubectl get --show-labels -o=wide'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias kgwowide='kubectl get --watch -o=wide'
alias kgpowowide='kubectl get pods --watch -o=wide'
alias kgdepwowide='kubectl get deployment --watch -o=wide'
alias kgsvcwowide='kubectl get service --watch -o=wide'
alias kgingwowide='kubectl get ingress --watch -o=wide'
alias kgcmwowide='kubectl get configmap --watch -o=wide'
alias kgsecwowide='kubectl get secret --watch -o=wide'
alias kgjowowide='kubectl get jobs --watch -o=wide'
alias kgcjowowide='kubectl get cronjobs --watch -o=wide'
alias kgnowowide='kubectl get nodes --watch -o=wide'
alias kgnswowide='kubectl get namespaces --watch -o=wide'
alias kgpvwowide='kubectl get persistentvolume --watch -o=wide'
alias kgpvcwowide='kubectl get persistentvolumeclaim --watch -o=wide'
alias kgsswowide='kubectl get statefulset --watch -o=wide'
alias kgojsonall='kubectl get -o=json --all-namespaces'
alias kgpoojsonall='kubectl get pods -o=json --all-namespaces'
alias kgdepojsonall='kubectl get deployment -o=json --all-namespaces'
alias kgsvcojsonall='kubectl get service -o=json --all-namespaces'
alias kgingojsonall='kubectl get ingress -o=json --all-namespaces'
alias kgcmojsonall='kubectl get configmap -o=json --all-namespaces'
alias kgsecojsonall='kubectl get secret -o=json --all-namespaces'
alias kgjoojsonall='kubectl get jobs -o=json --all-namespaces'
alias kgcjoojsonall='kubectl get cronjobs -o=json --all-namespaces'
alias kgnsojsonall='kubectl get namespaces -o=json --all-namespaces'
alias kgpvojsonall='kubectl get persistentvolume -o=json --all-namespaces'
alias kgpvcojsonall='kubectl get persistentvolumeclaim -o=json --all-namespaces'
alias kgssojsonall='kubectl get statefulset -o=json --all-namespaces'
alias kgallojson='kubectl get --all-namespaces -o=json'
alias kgpoallojson='kubectl get pods --all-namespaces -o=json'
alias kgdepallojson='kubectl get deployment --all-namespaces -o=json'
alias kgsvcallojson='kubectl get service --all-namespaces -o=json'
alias kgingallojson='kubectl get ingress --all-namespaces -o=json'
alias kgcmallojson='kubectl get configmap --all-namespaces -o=json'
alias kgsecallojson='kubectl get secret --all-namespaces -o=json'
alias kgjoallojson='kubectl get jobs --all-namespaces -o=json'
alias kgcjoallojson='kubectl get cronjobs --all-namespaces -o=json'
alias kgnsallojson='kubectl get namespaces --all-namespaces -o=json'
alias kgpvallojson='kubectl get persistentvolume --all-namespaces -o=json'
alias kgpvcallojson='kubectl get persistentvolumeclaim --all-namespaces -o=json'
alias kgssallojson='kubectl get statefulset --all-namespaces -o=json'
alias kgwojson='kubectl get --watch -o=json'
alias kgpowojson='kubectl get pods --watch -o=json'
alias kgdepwojson='kubectl get deployment --watch -o=json'
alias kgsvcwojson='kubectl get service --watch -o=json'
alias kgingwojson='kubectl get ingress --watch -o=json'
alias kgcmwojson='kubectl get configmap --watch -o=json'
alias kgsecwojson='kubectl get secret --watch -o=json'
alias kgjowojson='kubectl get jobs --watch -o=json'
alias kgcjowojson='kubectl get cronjobs --watch -o=json'
alias kgnowojson='kubectl get nodes --watch -o=json'
alias kgnswojson='kubectl get namespaces --watch -o=json'
alias kgpvwojson='kubectl get persistentvolume --watch -o=json'
alias kgpvcwojson='kubectl get persistentvolumeclaim --watch -o=json'
alias kgsswojson='kubectl get statefulset --watch -o=json'
alias kgonameall='kubectl get -o=name --all-namespaces'
alias kgpoonameall='kubectl get pods -o=name --all-namespaces'
alias kgdeponameall='kubectl get deployment -o=name --all-namespaces'
alias kgsvconameall='kubectl get service -o=name --all-namespaces'
alias kgingonameall='kubectl get ingress -o=name --all-namespaces'
alias kgcmonameall='kubectl get configmap -o=name --all-namespaces'
alias kgseconameall='kubectl get secret -o=name --all-namespaces'
alias kgjoonameall='kubectl get jobs -o=name --all-namespaces'
alias kgcjoonameall='kubectl get cronjobs -o=name --all-namespaces'
alias kgnsonameall='kubectl get namespaces -o=name --all-namespaces'
alias kgpvonameall='kubectl get persistentvolume -o=name --all-namespaces'
alias kgpvconameall='kubectl get persistentvolumeclaim -o=name --all-namespaces'
alias kgssonameall='kubectl get statefulset -o=name --all-namespaces'
alias kgalloname='kubectl get --all-namespaces -o=name'
alias kgpoalloname='kubectl get pods --all-namespaces -o=name'
alias kgdepalloname='kubectl get deployment --all-namespaces -o=name'
alias kgsvcalloname='kubectl get service --all-namespaces -o=name'
alias kgingalloname='kubectl get ingress --all-namespaces -o=name'
alias kgcmalloname='kubectl get configmap --all-namespaces -o=name'
alias kgsecalloname='kubectl get secret --all-namespaces -o=name'
alias kgjoalloname='kubectl get jobs --all-namespaces -o=name'
alias kgcjoalloname='kubectl get cronjobs --all-namespaces -o=name'
alias kgnsalloname='kubectl get namespaces --all-namespaces -o=name'
alias kgpvalloname='kubectl get persistentvolume --all-namespaces -o=name'
alias kgpvcalloname='kubectl get persistentvolumeclaim --all-namespaces -o=name'
alias kgssalloname='kubectl get statefulset --all-namespaces -o=name'
alias kgwoname='kubectl get --watch -o=name'
alias kgpowoname='kubectl get pods --watch -o=name'
alias kgdepwoname='kubectl get deployment --watch -o=name'
alias kgsvcwoname='kubectl get service --watch -o=name'
alias kgingwoname='kubectl get ingress --watch -o=name'
alias kgcmwoname='kubectl get configmap --watch -o=name'
alias kgsecwoname='kubectl get secret --watch -o=name'
alias kgjowoname='kubectl get jobs --watch -o=name'
alias kgcjowoname='kubectl get cronjobs --watch -o=name'
alias kgnowoname='kubectl get nodes --watch -o=name'
alias kgnswoname='kubectl get namespaces --watch -o=name'
alias kgpvwoname='kubectl get persistentvolume --watch -o=name'
alias kgpvcwoname='kubectl get persistentvolumeclaim --watch -o=name'
alias kgsswoname='kubectl get statefulset --watch -o=name'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgallw='kubectl get --all-namespaces --watch'
alias kgpoallw='kubectl get pods --all-namespaces --watch'
alias kgdepallw='kubectl get deployment --all-namespaces --watch'
alias kgsvcallw='kubectl get service --all-namespaces --watch'
alias kgingallw='kubectl get ingress --all-namespaces --watch'
alias kgcmallw='kubectl get configmap --all-namespaces --watch'
alias kgsecallw='kubectl get secret --all-namespaces --watch'
alias kgjoallw='kubectl get jobs --all-namespaces --watch'
alias kgcjoallw='kubectl get cronjobs --all-namespaces --watch'
alias kgnsallw='kubectl get namespaces --all-namespaces --watch'
alias kgpvallw='kubectl get persistentvolume --all-namespaces --watch'
alias kgpvcallw='kubectl get persistentvolumeclaim --all-namespaces --watch'
alias kgssallw='kubectl get statefulset --all-namespaces --watch'
alias kgwall='kubectl get --watch --all-namespaces'
alias kgpowall='kubectl get pods --watch --all-namespaces'
alias kgdepwall='kubectl get deployment --watch --all-namespaces'
alias kgsvcwall='kubectl get service --watch --all-namespaces'
alias kgingwall='kubectl get ingress --watch --all-namespaces'
alias kgcmwall='kubectl get configmap --watch --all-namespaces'
alias kgsecwall='kubectl get secret --watch --all-namespaces'
alias kgjowall='kubectl get jobs --watch --all-namespaces'
alias kgcjowall='kubectl get cronjobs --watch --all-namespaces'
alias kgnswall='kubectl get namespaces --watch --all-namespaces'
alias kgpvwall='kubectl get persistentvolume --watch --all-namespaces'
alias kgpvcwall='kubectl get persistentvolumeclaim --watch --all-namespaces'
alias kgsswall='kubectl get statefulset --watch --all-namespaces'
alias kgslw='kubectl get --show-labels --watch'
alias kgposlw='kubectl get pods --show-labels --watch'
alias kgdepslw='kubectl get deployment --show-labels --watch'
alias kgwsl='kubectl get --watch --show-labels'
alias kgpowsl='kubectl get pods --watch --show-labels'
alias kgdepwsl='kubectl get deployment --watch --show-labels'
alias kgallwoyaml='kubectl get --all-namespaces --watch -o=yaml'
alias kgpoallwoyaml='kubectl get pods --all-namespaces --watch -o=yaml'
alias kgdepallwoyaml='kubectl get deployment --all-namespaces --watch -o=yaml'
alias kgsvcallwoyaml='kubectl get service --all-namespaces --watch -o=yaml'
alias kgingallwoyaml='kubectl get ingress --all-namespaces --watch -o=yaml'
alias kgcmallwoyaml='kubectl get configmap --all-namespaces --watch -o=yaml'
alias kgsecallwoyaml='kubectl get secret --all-namespaces --watch -o=yaml'
alias kgjoallwoyaml='kubectl get jobs --all-namespaces --watch -o=yaml'
alias kgcjoallwoyaml='kubectl get cronjobs --all-namespaces --watch -o=yaml'
alias kgnsallwoyaml='kubectl get namespaces --all-namespaces --watch -o=yaml'
alias kgpvallwoyaml='kubectl get persistentvolume --all-namespaces --watch -o=yaml'
alias kgpvcallwoyaml='kubectl get persistentvolumeclaim --all-namespaces --watch -o=yaml'
alias kgssallwoyaml='kubectl get statefulset --all-namespaces --watch -o=yaml'
alias kgwoyamlall='kubectl get --watch -o=yaml --all-namespaces'
alias kgpowoyamlall='kubectl get pods --watch -o=yaml --all-namespaces'
alias kgdepwoyamlall='kubectl get deployment --watch -o=yaml --all-namespaces'
alias kgsvcwoyamlall='kubectl get service --watch -o=yaml --all-namespaces'
alias kgingwoyamlall='kubectl get ingress --watch -o=yaml --all-namespaces'
alias kgcmwoyamlall='kubectl get configmap --watch -o=yaml --all-namespaces'
alias kgsecwoyamlall='kubectl get secret --watch -o=yaml --all-namespaces'
alias kgjowoyamlall='kubectl get jobs --watch -o=yaml --all-namespaces'
alias kgcjowoyamlall='kubectl get cronjobs --watch -o=yaml --all-namespaces'
alias kgnswoyamlall='kubectl get namespaces --watch -o=yaml --all-namespaces'
alias kgpvwoyamlall='kubectl get persistentvolume --watch -o=yaml --all-namespaces'
alias kgpvcwoyamlall='kubectl get persistentvolumeclaim --watch -o=yaml --all-namespaces'
alias kgsswoyamlall='kubectl get statefulset --watch -o=yaml --all-namespaces'
alias kgwalloyaml='kubectl get --watch --all-namespaces -o=yaml'
alias kgpowalloyaml='kubectl get pods --watch --all-namespaces -o=yaml'
alias kgdepwalloyaml='kubectl get deployment --watch --all-namespaces -o=yaml'
alias kgsvcwalloyaml='kubectl get service --watch --all-namespaces -o=yaml'
alias kgingwalloyaml='kubectl get ingress --watch --all-namespaces -o=yaml'
alias kgcmwalloyaml='kubectl get configmap --watch --all-namespaces -o=yaml'
alias kgsecwalloyaml='kubectl get secret --watch --all-namespaces -o=yaml'
alias kgjowalloyaml='kubectl get jobs --watch --all-namespaces -o=yaml'
alias kgcjowalloyaml='kubectl get cronjobs --watch --all-namespaces -o=yaml'
alias kgnswalloyaml='kubectl get namespaces --watch --all-namespaces -o=yaml'
alias kgpvwalloyaml='kubectl get persistentvolume --watch --all-namespaces -o=yaml'
alias kgpvcwalloyaml='kubectl get persistentvolumeclaim --watch --all-namespaces -o=yaml'
alias kgsswalloyaml='kubectl get statefulset --watch --all-namespaces -o=yaml'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgallwowide='kubectl get --all-namespaces --watch -o=wide'
alias kgpoallwowide='kubectl get pods --all-namespaces --watch -o=wide'
alias kgdepallwowide='kubectl get deployment --all-namespaces --watch -o=wide'
alias kgsvcallwowide='kubectl get service --all-namespaces --watch -o=wide'
alias kgingallwowide='kubectl get ingress --all-namespaces --watch -o=wide'
alias kgcmallwowide='kubectl get configmap --all-namespaces --watch -o=wide'
alias kgsecallwowide='kubectl get secret --all-namespaces --watch -o=wide'
alias kgjoallwowide='kubectl get jobs --all-namespaces --watch -o=wide'
alias kgcjoallwowide='kubectl get cronjobs --all-namespaces --watch -o=wide'
alias kgnsallwowide='kubectl get namespaces --all-namespaces --watch -o=wide'
alias kgpvallwowide='kubectl get persistentvolume --all-namespaces --watch -o=wide'
alias kgpvcallwowide='kubectl get persistentvolumeclaim --all-namespaces --watch -o=wide'
alias kgssallwowide='kubectl get statefulset --all-namespaces --watch -o=wide'
alias kgwowideall='kubectl get --watch -o=wide --all-namespaces'
alias kgpowowideall='kubectl get pods --watch -o=wide --all-namespaces'
alias kgdepwowideall='kubectl get deployment --watch -o=wide --all-namespaces'
alias kgsvcwowideall='kubectl get service --watch -o=wide --all-namespaces'
alias kgingwowideall='kubectl get ingress --watch -o=wide --all-namespaces'
alias kgcmwowideall='kubectl get configmap --watch -o=wide --all-namespaces'
alias kgsecwowideall='kubectl get secret --watch -o=wide --all-namespaces'
alias kgjowowideall='kubectl get jobs --watch -o=wide --all-namespaces'
alias kgcjowowideall='kubectl get cronjobs --watch -o=wide --all-namespaces'
alias kgnswowideall='kubectl get namespaces --watch -o=wide --all-namespaces'
alias kgpvwowideall='kubectl get persistentvolume --watch -o=wide --all-namespaces'
alias kgpvcwowideall='kubectl get persistentvolumeclaim --watch -o=wide --all-namespaces'
alias kgsswowideall='kubectl get statefulset --watch -o=wide --all-namespaces'
alias kgwallowide='kubectl get --watch --all-namespaces -o=wide'
alias kgpowallowide='kubectl get pods --watch --all-namespaces -o=wide'
alias kgdepwallowide='kubectl get deployment --watch --all-namespaces -o=wide'
alias kgsvcwallowide='kubectl get service --watch --all-namespaces -o=wide'
alias kgingwallowide='kubectl get ingress --watch --all-namespaces -o=wide'
alias kgcmwallowide='kubectl get configmap --watch --all-namespaces -o=wide'
alias kgsecwallowide='kubectl get secret --watch --all-namespaces -o=wide'
alias kgjowallowide='kubectl get jobs --watch --all-namespaces -o=wide'
alias kgcjowallowide='kubectl get cronjobs --watch --all-namespaces -o=wide'
alias kgnswallowide='kubectl get namespaces --watch --all-namespaces -o=wide'
alias kgpvwallowide='kubectl get persistentvolume --watch --all-namespaces -o=wide'
alias kgpvcwallowide='kubectl get persistentvolumeclaim --watch --all-namespaces -o=wide'
alias kgsswallowide='kubectl get statefulset --watch --all-namespaces -o=wide'
alias kgslwowide='kubectl get --show-labels --watch -o=wide'
alias kgposlwowide='kubectl get pods --show-labels --watch -o=wide'
alias kgdepslwowide='kubectl get deployment --show-labels --watch -o=wide'
alias kgwowidesl='kubectl get --watch -o=wide --show-labels'
alias kgpowowidesl='kubectl get pods --watch -o=wide --show-labels'
alias kgdepwowidesl='kubectl get deployment --watch -o=wide --show-labels'
alias kgwslowide='kubectl get --watch --show-labels -o=wide'
alias kgpowslowide='kubectl get pods --watch --show-labels -o=wide'
alias kgdepwslowide='kubectl get deployment --watch --show-labels -o=wide'
alias kgallwojson='kubectl get --all-namespaces --watch -o=json'
alias kgpoallwojson='kubectl get pods --all-namespaces --watch -o=json'
alias kgdepallwojson='kubectl get deployment --all-namespaces --watch -o=json'
alias kgsvcallwojson='kubectl get service --all-namespaces --watch -o=json'
alias kgingallwojson='kubectl get ingress --all-namespaces --watch -o=json'
alias kgcmallwojson='kubectl get configmap --all-namespaces --watch -o=json'
alias kgsecallwojson='kubectl get secret --all-namespaces --watch -o=json'
alias kgjoallwojson='kubectl get jobs --all-namespaces --watch -o=json'
alias kgcjoallwojson='kubectl get cronjobs --all-namespaces --watch -o=json'
alias kgnsallwojson='kubectl get namespaces --all-namespaces --watch -o=json'
alias kgpvallwojson='kubectl get persistentvolume --all-namespaces --watch -o=json'
alias kgpvcallwojson='kubectl get persistentvolumeclaim --all-namespaces --watch -o=json'
alias kgssallwojson='kubectl get statefulset --all-namespaces --watch -o=json'
alias kgwojsonall='kubectl get --watch -o=json --all-namespaces'
alias kgpowojsonall='kubectl get pods --watch -o=json --all-namespaces'
alias kgdepwojsonall='kubectl get deployment --watch -o=json --all-namespaces'
alias kgsvcwojsonall='kubectl get service --watch -o=json --all-namespaces'
alias kgingwojsonall='kubectl get ingress --watch -o=json --all-namespaces'
alias kgcmwojsonall='kubectl get configmap --watch -o=json --all-namespaces'
alias kgsecwojsonall='kubectl get secret --watch -o=json --all-namespaces'
alias kgjowojsonall='kubectl get jobs --watch -o=json --all-namespaces'
alias kgcjowojsonall='kubectl get cronjobs --watch -o=json --all-namespaces'
alias kgnswojsonall='kubectl get namespaces --watch -o=json --all-namespaces'
alias kgpvwojsonall='kubectl get persistentvolume --watch -o=json --all-namespaces'
alias kgpvcwojsonall='kubectl get persistentvolumeclaim --watch -o=json --all-namespaces'
alias kgsswojsonall='kubectl get statefulset --watch -o=json --all-namespaces'
alias kgwallojson='kubectl get --watch --all-namespaces -o=json'
alias kgpowallojson='kubectl get pods --watch --all-namespaces -o=json'
alias kgdepwallojson='kubectl get deployment --watch --all-namespaces -o=json'
alias kgsvcwallojson='kubectl get service --watch --all-namespaces -o=json'
alias kgingwallojson='kubectl get ingress --watch --all-namespaces -o=json'
alias kgcmwallojson='kubectl get configmap --watch --all-namespaces -o=json'
alias kgsecwallojson='kubectl get secret --watch --all-namespaces -o=json'
alias kgjowallojson='kubectl get jobs --watch --all-namespaces -o=json'
alias kgcjowallojson='kubectl get cronjobs --watch --all-namespaces -o=json'
alias kgnswallojson='kubectl get namespaces --watch --all-namespaces -o=json'
alias kgpvwallojson='kubectl get persistentvolume --watch --all-namespaces -o=json'
alias kgpvcwallojson='kubectl get persistentvolumeclaim --watch --all-namespaces -o=json'
alias kgsswallojson='kubectl get statefulset --watch --all-namespaces -o=json'
alias kgallwoname='kubectl get --all-namespaces --watch -o=name'
alias kgpoallwoname='kubectl get pods --all-namespaces --watch -o=name'
alias kgdepallwoname='kubectl get deployment --all-namespaces --watch -o=name'
alias kgsvcallwoname='kubectl get service --all-namespaces --watch -o=name'
alias kgingallwoname='kubectl get ingress --all-namespaces --watch -o=name'
alias kgcmallwoname='kubectl get configmap --all-namespaces --watch -o=name'
alias kgsecallwoname='kubectl get secret --all-namespaces --watch -o=name'
alias kgjoallwoname='kubectl get jobs --all-namespaces --watch -o=name'
alias kgcjoallwoname='kubectl get cronjobs --all-namespaces --watch -o=name'
alias kgnsallwoname='kubectl get namespaces --all-namespaces --watch -o=name'
alias kgpvallwoname='kubectl get persistentvolume --all-namespaces --watch -o=name'
alias kgpvcallwoname='kubectl get persistentvolumeclaim --all-namespaces --watch -o=name'
alias kgssallwoname='kubectl get statefulset --all-namespaces --watch -o=name'
alias kgwonameall='kubectl get --watch -o=name --all-namespaces'
alias kgpowonameall='kubectl get pods --watch -o=name --all-namespaces'
alias kgdepwonameall='kubectl get deployment --watch -o=name --all-namespaces'
alias kgsvcwonameall='kubectl get service --watch -o=name --all-namespaces'
alias kgingwonameall='kubectl get ingress --watch -o=name --all-namespaces'
alias kgcmwonameall='kubectl get configmap --watch -o=name --all-namespaces'
alias kgsecwonameall='kubectl get secret --watch -o=name --all-namespaces'
alias kgjowonameall='kubectl get jobs --watch -o=name --all-namespaces'
alias kgcjowonameall='kubectl get cronjobs --watch -o=name --all-namespaces'
alias kgnswonameall='kubectl get namespaces --watch -o=name --all-namespaces'
alias kgpvwonameall='kubectl get persistentvolume --watch -o=name --all-namespaces'
alias kgpvcwonameall='kubectl get persistentvolumeclaim --watch -o=name --all-namespaces'
alias kgsswonameall='kubectl get statefulset --watch -o=name --all-namespaces'
alias kgwalloname='kubectl get --watch --all-namespaces -o=name'
alias kgpowalloname='kubectl get pods --watch --all-namespaces -o=name'
alias kgdepwalloname='kubectl get deployment --watch --all-namespaces -o=name'
alias kgsvcwalloname='kubectl get service --watch --all-namespaces -o=name'
alias kgingwalloname='kubectl get ingress --watch --all-namespaces -o=name'
alias kgcmwalloname='kubectl get configmap --watch --all-namespaces -o=name'
alias kgsecwalloname='kubectl get secret --watch --all-namespaces -o=name'
alias kgjowalloname='kubectl get jobs --watch --all-namespaces -o=name'
alias kgcjowalloname='kubectl get cronjobs --watch --all-namespaces -o=name'
alias kgnswalloname='kubectl get namespaces --watch --all-namespaces -o=name'
alias kgpvwalloname='kubectl get persistentvolume --watch --all-namespaces -o=name'
alias kgpvcwalloname='kubectl get persistentvolumeclaim --watch --all-namespaces -o=name'
alias kgsswalloname='kubectl get statefulset --watch --all-namespaces -o=name'
alias kgallslw='kubectl get --all-namespaces --show-labels --watch'
alias kgpoallslw='kubectl get pods --all-namespaces --show-labels --watch'
alias kgdepallslw='kubectl get deployment --all-namespaces --show-labels --watch'
alias kgallwsl='kubectl get --all-namespaces --watch --show-labels'
alias kgpoallwsl='kubectl get pods --all-namespaces --watch --show-labels'
alias kgdepallwsl='kubectl get deployment --all-namespaces --watch --show-labels'
alias kgslallw='kubectl get --show-labels --all-namespaces --watch'
alias kgposlallw='kubectl get pods --show-labels --all-namespaces --watch'
alias kgdepslallw='kubectl get deployment --show-labels --all-namespaces --watch'
alias kgslwall='kubectl get --show-labels --watch --all-namespaces'
alias kgposlwall='kubectl get pods --show-labels --watch --all-namespaces'
alias kgdepslwall='kubectl get deployment --show-labels --watch --all-namespaces'
alias kgwallsl='kubectl get --watch --all-namespaces --show-labels'
alias kgpowallsl='kubectl get pods --watch --all-namespaces --show-labels'
alias kgdepwallsl='kubectl get deployment --watch --all-namespaces --show-labels'
alias kgwslall='kubectl get --watch --show-labels --all-namespaces'
alias kgpowslall='kubectl get pods --watch --show-labels --all-namespaces'
alias kgdepwslall='kubectl get deployment --watch --show-labels --all-namespaces'
alias kgallslwowide='kubectl get --all-namespaces --show-labels --watch -o=wide'
alias kgpoallslwowide='kubectl get pods --all-namespaces --show-labels --watch -o=wide'
alias kgdepallslwowide='kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
alias kgallwowidesl='kubectl get --all-namespaces --watch -o=wide --show-labels'
alias kgpoallwowidesl='kubectl get pods --all-namespaces --watch -o=wide --show-labels'
alias kgdepallwowidesl='kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
alias kgallwslowide='kubectl get --all-namespaces --watch --show-labels -o=wide'
alias kgpoallwslowide='kubectl get pods --all-namespaces --watch --show-labels -o=wide'
alias kgdepallwslowide='kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
alias kgslallwowide='kubectl get --show-labels --all-namespaces --watch -o=wide'
alias kgposlallwowide='kubectl get pods --show-labels --all-namespaces --watch -o=wide'
alias kgdepslallwowide='kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
alias kgslwowideall='kubectl get --show-labels --watch -o=wide --all-namespaces'
alias kgposlwowideall='kubectl get pods --show-labels --watch -o=wide --all-namespaces'
alias kgdepslwowideall='kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
alias kgslwallowide='kubectl get --show-labels --watch --all-namespaces -o=wide'
alias kgposlwallowide='kubectl get pods --show-labels --watch --all-namespaces -o=wide'
alias kgdepslwallowide='kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
alias kgwowideallsl='kubectl get --watch -o=wide --all-namespaces --show-labels'
alias kgpowowideallsl='kubectl get pods --watch -o=wide --all-namespaces --show-labels'
alias kgdepwowideallsl='kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
alias kgwowideslall='kubectl get --watch -o=wide --show-labels --all-namespaces'
alias kgpowowideslall='kubectl get pods --watch -o=wide --show-labels --all-namespaces'
alias kgdepwowideslall='kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
alias kgwallowidesl='kubectl get --watch --all-namespaces -o=wide --show-labels'
alias kgpowallowidesl='kubectl get pods --watch --all-namespaces -o=wide --show-labels'
alias kgdepwallowidesl='kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
alias kgwallslowide='kubectl get --watch --all-namespaces --show-labels -o=wide'
alias kgpowallslowide='kubectl get pods --watch --all-namespaces --show-labels -o=wide'
alias kgdepwallslowide='kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
alias kgwslowideall='kubectl get --watch --show-labels -o=wide --all-namespaces'
alias kgpowslowideall='kubectl get pods --watch --show-labels -o=wide --all-namespaces'
alias kgdepwslowideall='kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
alias kgwslallowide='kubectl get --watch --show-labels --all-namespaces -o=wide'
alias kgpowslallowide='kubectl get pods --watch --show-labels --all-namespaces -o=wide'
alias kgdepwslallowide='kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
alias kgf='kubectl get --recursive -f'
alias kdf='kubectl describe --recursive -f'
alias krmf='kubectl delete --recursive -f'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgojsonf='kubectl get -o=json --recursive -f'
alias kgonamef='kubectl get -o=name --recursive -f'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgwf='kubectl get --watch --recursive -f'
alias kgwoyamlf='kubectl get --watch -o=yaml --recursive -f'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgwowidef='kubectl get --watch -o=wide --recursive -f'
alias kgwojsonf='kubectl get --watch -o=json --recursive -f'
alias kgwonamef='kubectl get --watch -o=name --recursive -f'
alias kgslwf='kubectl get --show-labels --watch --recursive -f'
alias kgwslf='kubectl get --watch --show-labels --recursive -f'
alias kgslwowidef='kubectl get --show-labels --watch -o=wide --recursive -f'
alias kgwowideslf='kubectl get --watch -o=wide --show-labels --recursive -f'
alias kgwslowidef='kubectl get --watch --show-labels -o=wide --recursive -f'
alias kgl='kubectl get -l'
alias kdl='kubectl describe -l'
alias krml='kubectl delete -l'
alias kgpol='kubectl get pods -l'
alias kdpol='kubectl describe pods -l'
alias krmpol='kubectl delete pods -l'
alias kgdepl='kubectl get deployment -l'
alias kddepl='kubectl describe deployment -l'
alias krmdepl='kubectl delete deployment -l'
alias kgsvcl='kubectl get service -l'
alias kdsvcl='kubectl describe service -l'
alias krmsvcl='kubectl delete service -l'
alias kgingl='kubectl get ingress -l'
alias kdingl='kubectl describe ingress -l'
alias krmingl='kubectl delete ingress -l'
alias kgcml='kubectl get configmap -l'
alias kdcml='kubectl describe configmap -l'
alias krmcml='kubectl delete configmap -l'
alias kgsecl='kubectl get secret -l'
alias kdsecl='kubectl describe secret -l'
alias krmsecl='kubectl delete secret -l'
alias kgjol='kubectl get jobs -l'
alias kdjol='kubectl describe jobs -l'
alias krmjol='kubectl delete jobs -l'
alias kgcjol='kubectl get cronjobs -l'
alias kdcjol='kubectl describe cronjobs -l'
alias krmcjol='kubectl delete cronjobs -l'
alias kgnol='kubectl get nodes -l'
alias kdnol='kubectl describe nodes -l'
alias kgnsl='kubectl get namespaces -l'
alias kdnsl='kubectl describe namespaces -l'
alias krmnsl='kubectl delete namespaces -l'
alias kgpvl='kubectl get persistentvolume -l'
alias kdpvl='kubectl describe persistentvolume -l'
alias krmpvl='kubectl delete persistentvolume -l'
alias kgpvcl='kubectl get persistentvolumeclaim -l'
alias kdpvcl='kubectl describe persistentvolumeclaim -l'
alias krmpvcl='kubectl delete persistentvolumeclaim -l'
alias kgssl='kubectl get statefulset -l'
alias kdssl='kubectl describe statefulset -l'
alias krmssl='kubectl delete statefulset -l'
alias kgoyamll='kubectl get -o=yaml -l'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias kgjooyamll='kubectl get jobs -o=yaml -l'
alias kgcjooyamll='kubectl get cronjobs -o=yaml -l'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgpvoyamll='kubectl get persistentvolume -o=yaml -l'
alias kgpvcoyamll='kubectl get persistentvolumeclaim -o=yaml -l'
alias kgssoyamll='kubectl get statefulset -o=yaml -l'
alias kgowidel='kubectl get -o=wide -l'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias kgjoowidel='kubectl get jobs -o=wide -l'
alias kgcjoowidel='kubectl get cronjobs -o=wide -l'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgpvowidel='kubectl get persistentvolume -o=wide -l'
alias kgpvcowidel='kubectl get persistentvolumeclaim -o=wide -l'
alias kgssowidel='kubectl get statefulset -o=wide -l'
alias kgojsonl='kubectl get -o=json -l'
alias kgpoojsonl='kubectl get pods -o=json -l'
alias kgdepojsonl='kubectl get deployment -o=json -l'
alias kgsvcojsonl='kubectl get service -o=json -l'
alias kgingojsonl='kubectl get ingress -o=json -l'
alias kgcmojsonl='kubectl get configmap -o=json -l'
alias kgsecojsonl='kubectl get secret -o=json -l'
alias kgjoojsonl='kubectl get jobs -o=json -l'
alias kgcjoojsonl='kubectl get cronjobs -o=json -l'
alias kgnoojsonl='kubectl get nodes -o=json -l'
alias kgnsojsonl='kubectl get namespaces -o=json -l'
alias kgpvojsonl='kubectl get persistentvolume -o=json -l'
alias kgpvcojsonl='kubectl get persistentvolumeclaim -o=json -l'
alias kgssojsonl='kubectl get statefulset -o=json -l'
alias kgonamel='kubectl get -o=name -l'
alias kgpoonamel='kubectl get pods -o=name -l'
alias kgdeponamel='kubectl get deployment -o=name -l'
alias kgsvconamel='kubectl get service -o=name -l'
alias kgingonamel='kubectl get ingress -o=name -l'
alias kgcmonamel='kubectl get configmap -o=name -l'
alias kgseconamel='kubectl get secret -o=name -l'
alias kgjoonamel='kubectl get jobs -o=name -l'
alias kgcjoonamel='kubectl get cronjobs -o=name -l'
alias kgnoonamel='kubectl get nodes -o=name -l'
alias kgnsonamel='kubectl get namespaces -o=name -l'
alias kgpvonamel='kubectl get persistentvolume -o=name -l'
alias kgpvconamel='kubectl get persistentvolumeclaim -o=name -l'
alias kgssonamel='kubectl get statefulset -o=name -l'
alias kgsll='kubectl get --show-labels -l'
alias kgposll='kubectl get pods --show-labels -l'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias kgwl='kubectl get --watch -l'
alias kgpowl='kubectl get pods --watch -l'
alias kgdepwl='kubectl get deployment --watch -l'
alias kgsvcwl='kubectl get service --watch -l'
alias kgingwl='kubectl get ingress --watch -l'
alias kgcmwl='kubectl get configmap --watch -l'
alias kgsecwl='kubectl get secret --watch -l'
alias kgjowl='kubectl get jobs --watch -l'
alias kgcjowl='kubectl get cronjobs --watch -l'
alias kgnowl='kubectl get nodes --watch -l'
alias kgnswl='kubectl get namespaces --watch -l'
alias kgpvwl='kubectl get persistentvolume --watch -l'
alias kgpvcwl='kubectl get persistentvolumeclaim --watch -l'
alias kgsswl='kubectl get statefulset --watch -l'
alias kgwoyamll='kubectl get --watch -o=yaml -l'
alias kgpowoyamll='kubectl get pods --watch -o=yaml -l'
alias kgdepwoyamll='kubectl get deployment --watch -o=yaml -l'
alias kgsvcwoyamll='kubectl get service --watch -o=yaml -l'
alias kgingwoyamll='kubectl get ingress --watch -o=yaml -l'
alias kgcmwoyamll='kubectl get configmap --watch -o=yaml -l'
alias kgsecwoyamll='kubectl get secret --watch -o=yaml -l'
alias kgjowoyamll='kubectl get jobs --watch -o=yaml -l'
alias kgcjowoyamll='kubectl get cronjobs --watch -o=yaml -l'
alias kgnowoyamll='kubectl get nodes --watch -o=yaml -l'
alias kgnswoyamll='kubectl get namespaces --watch -o=yaml -l'
alias kgpvwoyamll='kubectl get persistentvolume --watch -o=yaml -l'
alias kgpvcwoyamll='kubectl get persistentvolumeclaim --watch -o=yaml -l'
alias kgsswoyamll='kubectl get statefulset --watch -o=yaml -l'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias kgwowidel='kubectl get --watch -o=wide -l'
alias kgpowowidel='kubectl get pods --watch -o=wide -l'
alias kgdepwowidel='kubectl get deployment --watch -o=wide -l'
alias kgsvcwowidel='kubectl get service --watch -o=wide -l'
alias kgingwowidel='kubectl get ingress --watch -o=wide -l'
alias kgcmwowidel='kubectl get configmap --watch -o=wide -l'
alias kgsecwowidel='kubectl get secret --watch -o=wide -l'
alias kgjowowidel='kubectl get jobs --watch -o=wide -l'
alias kgcjowowidel='kubectl get cronjobs --watch -o=wide -l'
alias kgnowowidel='kubectl get nodes --watch -o=wide -l'
alias kgnswowidel='kubectl get namespaces --watch -o=wide -l'
alias kgpvwowidel='kubectl get persistentvolume --watch -o=wide -l'
alias kgpvcwowidel='kubectl get persistentvolumeclaim --watch -o=wide -l'
alias kgsswowidel='kubectl get statefulset --watch -o=wide -l'
alias kgwojsonl='kubectl get --watch -o=json -l'
alias kgpowojsonl='kubectl get pods --watch -o=json -l'
alias kgdepwojsonl='kubectl get deployment --watch -o=json -l'
alias kgsvcwojsonl='kubectl get service --watch -o=json -l'
alias kgingwojsonl='kubectl get ingress --watch -o=json -l'
alias kgcmwojsonl='kubectl get configmap --watch -o=json -l'
alias kgsecwojsonl='kubectl get secret --watch -o=json -l'
alias kgjowojsonl='kubectl get jobs --watch -o=json -l'
alias kgcjowojsonl='kubectl get cronjobs --watch -o=json -l'
alias kgnowojsonl='kubectl get nodes --watch -o=json -l'
alias kgnswojsonl='kubectl get namespaces --watch -o=json -l'
alias kgpvwojsonl='kubectl get persistentvolume --watch -o=json -l'
alias kgpvcwojsonl='kubectl get persistentvolumeclaim --watch -o=json -l'
alias kgsswojsonl='kubectl get statefulset --watch -o=json -l'
alias kgwonamel='kubectl get --watch -o=name -l'
alias kgpowonamel='kubectl get pods --watch -o=name -l'
alias kgdepwonamel='kubectl get deployment --watch -o=name -l'
alias kgsvcwonamel='kubectl get service --watch -o=name -l'
alias kgingwonamel='kubectl get ingress --watch -o=name -l'
alias kgcmwonamel='kubectl get configmap --watch -o=name -l'
alias kgsecwonamel='kubectl get secret --watch -o=name -l'
alias kgjowonamel='kubectl get jobs --watch -o=name -l'
alias kgcjowonamel='kubectl get cronjobs --watch -o=name -l'
alias kgnowonamel='kubectl get nodes --watch -o=name -l'
alias kgnswonamel='kubectl get namespaces --watch -o=name -l'
alias kgpvwonamel='kubectl get persistentvolume --watch -o=name -l'
alias kgpvcwonamel='kubectl get persistentvolumeclaim --watch -o=name -l'
alias kgsswonamel='kubectl get statefulset --watch -o=name -l'
alias kgslwl='kubectl get --show-labels --watch -l'
alias kgposlwl='kubectl get pods --show-labels --watch -l'
alias kgdepslwl='kubectl get deployment --show-labels --watch -l'
alias kgwsll='kubectl get --watch --show-labels -l'
alias kgpowsll='kubectl get pods --watch --show-labels -l'
alias kgdepwsll='kubectl get deployment --watch --show-labels -l'
alias kgslwowidel='kubectl get --show-labels --watch -o=wide -l'
alias kgposlwowidel='kubectl get pods --show-labels --watch -o=wide -l'
alias kgdepslwowidel='kubectl get deployment --show-labels --watch -o=wide -l'
alias kgwowidesll='kubectl get --watch -o=wide --show-labels -l'
alias kgpowowidesll='kubectl get pods --watch -o=wide --show-labels -l'
alias kgdepwowidesll='kubectl get deployment --watch -o=wide --show-labels -l'
alias kgwslowidel='kubectl get --watch --show-labels -o=wide -l'
alias kgpowslowidel='kubectl get pods --watch --show-labels -o=wide -l'
alias kgdepwslowidel='kubectl get deployment --watch --show-labels -o=wide -l'
